--- # Configuration
    PORT: "80"
    ENVIRONMENT: "production"
    DATA: 
        MONGO_HOST: "mongodb+srv://gabriel2mm:gabriel2mm@cluster0.u67ah.gcp.mongodb.net/GerenciamentoOS"
    SECRET: "meuprojeto"
    UPLOAD_DIR: "uploads"