--- # Configuration
    PORT: "8080"
    ENVIRONMENT: "production"
    DATA: 
        MONGO_HOST: "mongodb+srv://adriano:adriano@cluster0.u67ah.gcp.mongodb.net/GerenciamentoOS"
    SECRET: "meuprojeto"
    UPLOAD_DIR: "uploads"